// <auto-generated />
namespace Pure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class data0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data0));
        
        string IMigrationMetadata.Id
        {
            get { return "201910280855132_data0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
