// <auto-generated />
namespace Pure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class init11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init11));
        
        string IMigrationMetadata.Id
        {
            get { return "201911140829563_init 11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
